const images =  {
    allMountain1: require('./img/photos/allMountain/allMountain1.jpg').default,
    allMountain2: require('./img/photos/allMountain/allMountain2.jpg').default,
    allMountain3: require('./img/photos/allMountain/allMountain3.jpg').default,
    allMountain4: require('./img/photos/allMountain/allMountain4.jpg').default,
    allMountain5: require('./img/photos/allMountain/allMountain5.jpg').default,
    allMountain6: require('./img/photos/allMountain/allMountain6.jpg').default,
    allMountain7: require('./img/photos/allMountain/allMountain7.jpg').default,
    allMountain8: require('./img/photos/allMountain/allMountain8.JPG').default,
    allMountain9: require('./img/photos/allMountain/allMountain9.jpg').default,
    allMountain10: require('./img/photos/allMountain/allMountain10.jpg').default,
    allMountain11: require('./img/photos/allMountain/allMountain11.jpg').default,
    enduro1: require('./img/photos/enduro/enduro1.jpg').default,
    enduro2: require('./img/photos/enduro/enduro2.jpg').default,
    enduro3: require('./img/photos/enduro/enduro3.jpg').default,
    enduro4: require('./img/photos/enduro/enduro4.jpg').default,
    enduro5: require('./img/photos/enduro/enduro5.jpg').default,
    enduro6: require('./img/photos/enduro/enduro6.JPG').default,
    enduro7: require('./img/photos/enduro/enduro7.jpg').default,
    enduro8: require('./img/photos/enduro/enduro8.jpg').default,
    enfants1: require('./img/photos/enfants/enfants1.jpg').default,
    enfants2: require('./img/photos/enfants/enfants2.jpg').default,
    enfants3: require('./img/photos/enfants/enfants3.jpg').default,
    enfants4: require('./img/photos/enfants/enfants4.jpg').default,
    enfants5: require('./img/photos/enfants/enfants5.jpg').default,
    enfants6: require('./img/photos/enfants/enfants6.JPG').default,
    enfants7: require('./img/photos/enfants/enfants7.JPG').default,
    enfants8: require('./img/photos/enfants/enfants8.JPG').default,
    enfants9: require('./img/photos/enfants/enfants9.JPG').default,
    enfants10: require('./img/photos/enfants/enfants10.jpg').default,
    enfants11: require('./img/photos/enfants/enfants11.JPG').default,
    enfants12: require('./img/photos/enfants/enfants12.jpg').default,
    freeride1: require('./img/photos/freeRide/freeride1.jpg').default,
    freeride2: require('./img/photos/freeRide/freeride2.JPG').default,
    freeride3: require('./img/photos/freeRide/freeride3.jpg').default,
    freeride4: require('./img/photos/freeRide/freeride4.jpg').default,
    freeride5: require('./img/photos/freeRide/freeride5.JPG').default,
    freeride6: require('./img/photos/freeRide/freeride6.JPG').default,
    freeride7: require('./img/photos/freeRide/freeride7.jpg').default,
    freeride8: require('./img/photos/freeRide/freeride8.JPG').default,
    freeride9: require('./img/photos/freeRide/freeride9.jpg').default,
    freeride10: require('./img/photos/freeRide/freeride10.JPG').default,
    freeride11: require('./img/photos/freeRide/freeride11.JPG').default
}

export default images;