const images =  {
    allMountain1: require('./img/photos/allMountain/allMountain1.jpg'),
    allMountain2: require('./img/photos/allMountain/allMountain2.jpg'),
    allMountain3: require('./img/photos/allMountain/allMountain3.jpg'),
    allMountain4: require('./img/photos/allMountain/allMountain4.jpg'),
    allMountain5: require('./img/photos/allMountain/allMountain5.jpg'),
    allMountain6: require('./img/photos/allMountain/allMountain6.jpg'),
    allMountain7: require('./img/photos/allMountain/allMountain7.jpg'),
    allMountain8: require('./img/photos/allMountain/allMountain8.jpg'),
    allMountain9: require('./img/photos/allMountain/allMountain9.jpg'),
    allMountain10: require('./img/photos/allMountain/allMountain10.jpg'),
    allMountain11: require('./img/photos/allMountain/allMountain11.jpg'),
    enduro1: require('./img/photos/enduro/enduro1.jpg'),
    enduro2: require('./img/photos/enduro/enduro2.jpg'),
    enduro3: require('./img/photos/enduro/enduro3.jpg'),
    enduro4: require('./img/photos/enduro/enduro4.jpg'),
    enduro5: require('./img/photos/enduro/enduro5.jpg'),
    enduro6: require('./img/photos/enduro/enduro6.jpg'),
    enduro7: require('./img/photos/enduro/enduro7.jpg'),
    enduro8: require('./img/photos/enduro/enduro8.jpg'),
    enfants1: require('./img/photos/enfants/enfants1.jpg'),
    enfants2: require('./img/photos/enfants/enfants2.jpg'),
    enfants3: require('./img/photos/enfants/enfants3.jpg'),
    enfants4: require('./img/photos/enfants/enfants4.jpg'),
    enfants5: require('./img/photos/enfants/enfants5.jpg'),
    enfants6: require('./img/photos/enfants/enfants6.jpg'),
    enfants7: require('./img/photos/enfants/enfants7.jpg'),
    enfants8: require('./img/photos/enfants/enfants8.jpg'),
    enfants9: require('./img/photos/enfants/enfants9.jpg'),
    enfants10: require('./img/photos/enfants/enfants10.jpg'),
    enfants11: require('./img/photos/enfants/enfants11.jpg'),
    enfants12: require('./img/photos/enfants/enfants12.jpg'),
    freeride1: require('./img/photos/freeRide/freeride1.jpg'),
    freeride2: require('./img/photos/freeRide/freeride2.jpg'),
    freeride3: require('./img/photos/freeRide/freeride3.jpg'),
    freeride4: require('./img/photos/freeRide/freeride4.jpg'),
    freeride5: require('./img/photos/freeRide/freeride5.jpg'),
    freeride6: require('./img/photos/freeRide/freeride6.jpg'),
    freeride7: require('./img/photos/freeRide/freeride7.jpg'),
    freeride8: require('./img/photos/freeRide/freeride8.jpg'),
    freeride9: require('./img/photos/freeRide/freeride9.jpg'),
    freeride10: require('./img/photos/freeRide/freeride10.jpg'),
    freeride11: require('./img/photos/freeRide/freeride11.jpg')
}

export default images;